version: "3.8"
name: buildCache
#
services:
  gradleBuildCache:
    image: gradle/build-cache-node
    ports:
      - "5071:5071"

    volumes:
      - ${PWD}/config:/var/config
      - buildCache:/data
    command:
      - "-c=/var/config"

volumes:
  buildCache: