openapi: 3.0.3
info:
  version: 1.0.0
  title: Example2
servers:
  - url: http://localhost:8080/api

paths:
  /example2:
    get:
      operationId: getSomethingElse
      tags:
        - exampleQuery2
      description: example
      responses:
        "200":
          description: example
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Example2Response'

components:
  schemas:

    Example2Response:
      type: object
      properties:
        values:
          type: array
          items:
            type: integer
